name: theport
recipe: drupal9
config:
  php: '8.0'
  composer_version: '2.2.7'
  webroot: web
  via: apache:2.4
  database: mysql:5.7
  xdebug: false
  drush: composer
services:
  appserver:
    build:
      - composer install
  db:
    type: phpmyadmin
    hosts:
      - database
  mail:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver
proxy:
  db:
    - db.theport.lndo.site
  mail:
    - mail.theport.lndo.site