<?php

use Drupal\Core\Url;

/**
 * Implements hook_help()
 * 
 * @param $route_name
 */
function projects_page_help($route_name) {
  switch ($route_name) {
    case 'help.page.projects_page':
      return t("This module activates the Projects page.");
  }
}

/**
 * Implements hook_preprocess_html()
 * 
 * @param $variables
 */
function projects_page_preprocess_html(&$variables) {
  $endpoint = Url::fromRoute('projects_page.projects.json')->toString();

  $preload_json = [
    '#tag' => 'link',
    '#attributes' => [
      'rel' => 'preload',
      'href' => $endpoint,
      'as' => 'fetch',
      'crossorigin' => '',
    ],
  ];
  $variables['page']['#attached']['html_head'][] = [$preload_json, 'preload_json'];
  $variables['#attached']['library'][] = 'core/drupalSettings';
  $variables['#attached']['drupalSettings']['projects_page']['endpoint'] = $endpoint;
}