css_adjust_sort_browsers: false
css_adjust_sort_external: false
css_defer: 1
css_defer_admin: false
css_defer_external: false
css_defer_js_code: 0
css_preprocess: false
css_translate: null
js_adjust_sort_browsers: false
js_adjust_sort_external: false
js_async: false
js_async_in_header: false
js_defer: 0
js_preprocess: false
prefetch: null
_core:
  default_config_hash: DIsgflQr3uh-j0GWnPgGhZn0yCXGdImu4-u1m2Uv9IY
js_footer: null
js_remove_console_log: false
unified_multisite_dir: null
