ignored_config_entities:
  - 'backup_migrate.*'
  - 'bootstrap5.*'
  - 'block.block.bootstrap5.*'
  - 'seven.*'
  - 'block.block.seven.*'
  - 'captcha.*'
  - 'comment.*'
  - 'dblog.*'
  - 'editor.*'
  - 'matomo.*'
  - 'user.*'
  - 'filter.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
