_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  backup_migrate: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  change_author_action: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contextual: 0
  country: 0
  crop: 0
  csp: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gutenberg: 0
  help: 0
  image: 0
  image_captcha: 0
  image_widget_crop: 0
  link: 0
  matomo: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  minifyhtml: 0
  node: 0
  node_title_validation: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  schema_event: 0
  schema_metatag: 0
  schema_person: 0
  shortcut: 0
  summary_word_limit: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_bulk_edit: 0
  views_ui: 0
  webform: 0
  webform_spam_words: 0
  webform_submission_export_import: 0
  webform_ui: 0
  webp: 0
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  seven: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  theport: 0
profile: standard
