_core:
  default_config_hash: o4-eDkmTmVdUICtL1VxWD3S9Ze8kNq_lHj6DskF8U8o
report-only:
  enable: false
  directives:
    script-src:
      base: self
    script-src-attr:
      base: self
      flags:
        - unsafe-inline
    script-src-elem:
      base: self
    style-src:
      base: self
      sources:
        - 'https://fonts.googleapis.com'
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      sources:
        - 'https://fonts.googleapis.com'
    frame-ancestors:
      base: self
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    script-src:
      base: self
      flags:
        - unsafe-eval
    style-src:
      base: self
      flags:
        - unsafe-inline
    frame-ancestors:
      base: self
      sources:
        - 'https://cds.cern.ch/'
  reporting:
    plugin: sitelog
