node_title_validation_config:
  comma-article: 0
  exclude-article: ''
  min-article: '1'
  max-article: '255'
  min-wc-article: '1'
  max-wc-article: '25'
  unique-article: 0
  comma-event: 0
  exclude-event: ''
  min-event: '1'
  max-event: '255'
  min-wc-event: '1'
  max-wc-event: '25'
  unique-event: 0
  comma-page: 0
  exclude-page: ''
  min-page: '1'
  max-page: '255'
  min-wc-page: '1'
  max-wc-page: '25'
  unique-page: 0
  comma-participant: 0
  exclude-participant: '!,@,#,$,%,^,&,*,(,),1,2,3,4,5,6,7,8,9,0'
  min-participant: '1'
  max-participant: '255'
  min-wc-participant: '2'
  max-wc-participant: '10'
  unique-participant: 1
  comma-partner: 0
  exclude-partner: ''
  min-partner: '1'
  max-partner: '255'
  min-wc-partner: '1'
  max-wc-partner: '25'
  unique-partner: 1
  comma-project: 0
  exclude-project: ''
  min-project: '1'
  max-project: '255'
  min-wc-project: '1'
  max-wc-project: '25'
  unique-project: 0
  unique: 0
_core:
  default_config_hash: 5p2lzpRAbNnhbgkvO2MKkxtc2QOBeMRkWubKyc7HYFE
