features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
b5_top_container: container
b5_top_container_config: ''
b5_body_schema: light
b5_body_bg_schema: light
b5_navbar_schema: light
b5_navbar_bg_schema: primary
b5_footer_schema: dark
b5_footer_bg_schema: dark
subtheme_folder: themes/custom
subtheme_name: ''
subtheme_machine_name: ''
